### ISSUE TITLE
Known predictiors needs to be a dataframe and names are lost 

### ISSUE THREAD

**Issue by YimenAraya-Ajoy** [squidgroup/squidSim#28]
know predictors need to be matrix or data frame. Names of variables need to be inputed manually, because they are lost if inputed as vectors.

**Comment by joelpick** [comment]
@YimenAraya-Ajoy do you remember more specifically what this was about??

**Comment by joelpick** [comment]
I think I have put in error messages that make this clear, and added to documentation
